### ISSUE TITLE
Raw data retrieval - We are currently updating the system. Thank you! 

### ISSUE THREAD

**Issue by jjkoehorst** [biocore/emp#111]
I was looking for the raw datasets and I think it should be available at https://qiita.ucsd.edu/emp/ but its currently being updated? Any news on how long this will take or did I just stumble upon it by accident? 

Also is this data maybe available through EBI / ENA?

**Comment by antgonza** [comment]
The update has been scheduled for a few weeks now and started a few minutes ago; we expect it to be back before the end of the day. If you have the EBI-ENA accession, then that's another option. Hope this helps and sorry for the inconvenience.

**Comment by cuttlefishh** [comment]
For the datasets in the 2017 paper, you can get the data from EBI/ENA as well as the FTP site and Zenodo. Please find the links at earthmicrobiome.org. 

Luke

Em 15 de jul de 2019, à(s) 08:16, Antonio Gonzalez <notifications@github.com> escreveu:
