### ISSUE TITLE
Fix metadata for the studies that still don't have it, or delete those studies

### ISSUE THREAD

**Issue by rob-knight** [biocore/emp#17]
It is critical that at launch we can say we are providing a set of studies with good metadata. We therefore need to set a hard deadline for studies with sufficient metadata to actually understand the study in isolation or in combination, then delete the studies that don't meet this criterion (rather than continuing to attempt to extract metadata from people who won't provide it and having the project look bad overall).

**Comment by cuttlefishh** [comment]
I have two ipython notebooks using pandas to (1) explore metadata across all studies and then (2) "refine" metadata by adding fixed columns per each mapping file. I am working with Gail to make sure we have the best version of metadata for each study.
