### ISSUE TITLE
map of the earth containing location of all samples (and sub-maps colored by sample site)

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/emp#2]

**Comment by cuttlefishh** [comment]
@mortonjt -- Would you like to adapt your basemap code for this issue?

**Comment by mortonjt** [comment]
I'm game

**Comment by mortonjt** [comment]
Sorry. Got late into the conversion.  Basemap is statically generated, so no zooming capabilities are enabled. I do have code to generate these data to highlight different metadata.  Is that what is needed?

**Comment by cuttlefishh** [comment]
Yes, that's it exactly. Priorities are roughly:

1. A 2D static map that we can color by any metadata variable, categorical or gradient. Basemap.
2. A 2D dynamic map. `ili seems better suited than bokeh by first approximation.
3. A 3D dynamic map. `ili or Emperor.

On that note, is Emperor capable of plotting metadata on any 3D array of points? This general functionality would be great. @ElDeveloper

**Comment by ElDeveloper** [comment]
Yes, this should be possible, the flag you would be looking for is `-a`,
and you would need to have all numeric data in those metadata columns.
I've never tried plotting latitude and longitude + PC1, but it should
work, if not we can make it happen.

**Comment by cuttlefishh** [comment]
That would be awesome! I'll play around with that over break.

**Comment by mortonjt** [comment]
Not sure about what would be the best way about this?  Would you like IPython notebooks to plot all of the static maps - similar to what's going on in https://github.com/biocore/American-Gut?

Also, not sure if ili is designed to handle maps.  And Emperor is definitely not built for that.  I'd think that Google maps may be more appropriate.  However, the API is has already been [depreciated](http://stackoverflow.com/questions/3609344/alternative-map-apis-like-google-maps).  So I'm not sure what the best alternative is - but there is a long list of [options](http://stackoverflow.com/questions/3609344/alternative-map-apis-like-google-maps) that can be explored.

**Comment by ElDeveloper** [comment]
Ah, this just reminded me, we've done some "interactive map stuff" in
Platypus, that works with the IPython notebook, see here:
http://nbviewer.ipython.org/github/biocore/Platypus-Conquistador/blob/master/ipynbs/Chasing_Platypus_via_MG-RAST.ipynb

**Comment by mortonjt** [comment]
Whoa.  That's awesome!

**Comment by cuttlefishh** [comment]
Done by me (Luke T.) and Josh Lefler for EMP paper (Release 1).
