### ISSUE TITLE
merge per-study OTU tables to single master OTU table and post to GitHub

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/emp#25]
The OTU table merge operation is still running (in parallel using [this code](https://github.com/EarthMicrobiomeProject/isme14/blob/master/code/scripts/parallel_merge_otu_tables.py)), and I'm not sure when it's going to complete. 

**To be on the safe side**, we should begin performing analysis on OTU tables independently, as was done for the AAAS meeting. A lot of progress has been made on the making the sparse OTU table objects more efficient, but there is still work to do as is being discussed [here](https://github.com/biom-format/biom-format/issues/41) and [here](https://github.com/biom-format/biom-format/issues/42).

**Comment by cuttlefishh** [comment]
Files are posted to ftp://ftp.microbio.me/emp/release1.
