### ISSUE TITLE
PCoA plot of all samples

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/emp#3]
this may be challenging as it requires all samples in a single OTU table, and we're still having issues with tables of that size despite a lot of improvements to the biom-format objects

**Comment by cuttlefishh** [comment]
My how time as passed. As of Dec 2015, @wasade has figured out that whole biom-format thing and is working on faster UniFrac. @ElDeveloper and @mortonjt are working on faster Emperor. 

Recent update from @wasade on faster UniFrac with smaller biom tables (optimization with large biom tables continues):

    We can compute unweighted unifrac on 1000 samples 
    (AG, random sample of 1k rarefied set, against gg 97%) 
    in about 30s on a laptop. 50s if you account for parse of 
    the input tree and table prior to bdiv. Peak total memory, 
    including threads is <1GB.
