### ISSUE TITLE
load 10k data files

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/emp#35]
- [ ] BIOM table (will do by posting on S3 and providing a bash script which `wget`s it)
- [x] master mapping file
- [ ] tree
- [ ] new reference sequences 
- [ ] taxonomy assignments (loaded into BIOM, ideally)

Currently waiting on data files from @seangibbons.

**Comment by cuttlefishh** [comment]
Closing this issue because @josenavas is working with 20k-sample biom tables on barnacle at UCSD.

**Comment by cuttlefishh** [comment]
To clarify: Jose is making CR and OR biom tables. Colin Brislawn is making Swarm (v2) biom tables.
