### ISSUE TITLE
greengenes coverage tree: how much of greengenes is covered by samples, and how much does EMP add to greengenes?

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/emp#4]

**Comment by cuttlefishh** [comment]
@gregcaporaso suggested to use [ETE](http://etetoolkit.org) (python package: ete3) -- does it scale to thousands of nodes and leaves?

@rob-knight said if ETE doesn't scale, talk to Juergen at Calit2 about using their network display tool on the big wall (VROOM). Key is to color nodes and leaves by metadata (ETE does this).

**Comment by cuttlefishh** [comment]
@tanaes Would you be interested in working on this figure? Basically we want a 16S tree showing how much new diversity is added by the EMP. It could be relative to the existing Greengenes tree, Silva tree, or something else.

**Comment by tanaes** [comment]
Definitely interested in contributing.

Some thoughts:

1. How do we define new diversity? is the interesting and relevant question
how much new diversity at a certain branch depth (to mitigate influence of
noise)? In the latter case, one might imagine a tree with collapsed clades,
each with a pie chart indicating fraction of novel diversity contributed at
>= 85% identity or something. Alternatively, a line graph along tree depth
showing cumulative proportion of new nodes.

2. Are there other aspects of the distribution of this novelty we could
highlight in this figure? For example, we could imagine shading the
annotation of the tree somehow based on environment of origin; perhaps
restricting to OTUs to novel ones found in >1 study, and indicating which
top-level categories are contributing the most novel diversity...

**Comment by cuttlefishh** [comment]
Glad you are interested! Both are good ideas. Let's discuss tomorrow.

**Comment by wasade** [comment]
One thing to keep in mind, the silva and greengenes are based on full
length. It is not assured that the v4 reads in the EMP will map uniquely,
so some tips may appear "unobserved" when they're actually ambiguous.

**Comment by cuttlefishh** [comment]
This analysis was done be @tanaes for the EMP paper (Release 1).
