### ISSUE TITLE
Post and improve SOPs

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/emp#47]
Post the iPython notebooks folks have been using for data processing. We can then work to improve their documentation and verify reproducibility.

Begin writing overview of processing steps in wiki.

Open questions:
- How should we divide up the various pipelines? e.g. Should demultiplexing and quality filtering be in the same or different notebooks?
- How do we verify we are using the same software environments? Maybe have a software deployment wiki page or software deployment notebook?

**Comment by josenavas** [comment]
Demultiplexing and quality filtering: the idea is that we are going to grab the demultiplexed and quality filtered files from Qiita.

Software environments: everything that is a python package will be listed in the setup.py, with versions. If something is not a python software, is going to be listed in the INSTALL.md document from the repo, with versions listed.

**Comment by josenavas** [comment]
Alternatively, if we have conda recipes for all the non-python packages, we can setup all of those easier, so less problems :-)

**Comment by colinbrislawn** [comment]
:+1: for conda. I want each and every program, including qiime itself, in a conda package.

We have been making OK progress at www.github.com/biocore/conda-recipes. The day will come!

**Comment by colinbrislawn** [comment]
@cuttlefishh @josenavas Is there a preferred parallelization toolkit for this project? I've looking to run `vsearch --derepfulllength` on a bunch of files, but was not sure if I should be using bash, or python, or the Jupyter server, or qiime parallel. 
https://github.com/biocore/qiime/blob/master/qiime/parallel/poller.py

Suggestions welcome.

**Comment by josenavas** [comment]
Hi @colinbrislawn not at this point - except qiime parallel, feel free to use whatever is easier for you

**Comment by cuttlefishh** [comment]
Hi @colinbrislawn, how is the SOP wiki coming along?

**Comment by colinbrislawn** [comment]
Haha, it's not. I've been focused on an internal project.

What's the expected timeline on this?

**Comment by cuttlefishh** [comment]
That's ok; I know how it goes. I put up my notes (tables) on processing. Feel free to edit as you see fit.

There isn't a hard deadline. It would be great if we had the SOPs and Notebooks in place by the next EMP meeting on April 13. 

Simultaneously I'm working with an undergrad to get the metadata in good shape, you're doing Swarm testing, Jose is working on the alignment and tree building, and Daniel is working on the beta diversity algorithm. With those items sorted we can run the notebooks for primary processing, test analyses on the 2k and 20k test sets, and then run them on the final 20k set using the notebooks. 

The EMP20k has been a slightly lower priority for folks especially as we are working on the EMP500 project. But I expect we'll be ramping up soon.

**Comment by colinbrislawn** [comment]
I think I can do SOPs by end of March, then get feedback before the meeting in April. 

Swarm is unexpectedly difficult for multiple projects, and I'd like some support with part of it. I can describe my problem in a new issue or during our call tomorrow. I'm not sure what my timeline is for that.

**Comment by josenavas** [comment]
@colinbrislawn feel free to drop me an email describing the issues that you're finding - from there we can communicate with more people to actual find the solution - what do you think?

**Comment by colinbrislawn** [comment]
Sounds good! I'll assemble a toy example of what I'm trying to do and see who's interested in helping. Thank you @josenavas. I really appreciate the support.

**Comment by colinbrislawn** [comment]
Suggestion to run share scripts using the American Gut project as a template.

**Comment by colinbrislawn** [comment]
Looks like the analysis notebooks are up to date, thanks to Luke @cuttlefishh Thompson. Thanks Luke!

**Comment by cuttlefishh** [comment]
Thanks @colinbrislawn! I have been reviewing other issues and closing ones that are completed. If you want to help with that, please go ahead!
