### ISSUE TITLE
website: EMP Protocols and Standards

### ISSUE THREAD

**Issue by cuttlefishh** [biocore/emp#50]
These need to be carefully checked and updated. Known issues:
- Sequencing primers are incorrect
- Fungal ITS protocol missing
- Analysis page refers to closed-ref only

**Comment by ackermag** [comment]
Update shipping protocols to include raw samples

**Comment by cuttlefishh** [comment]
I changed the script and added a link to Jai's PeerJ paper, as per @gregcaporaso suggestions.

@colinbrislawn here is the page link: http://www.earthmicrobiome.org/emp-standard-protocols/16s-taxonomic-assignments/

**Comment by cuttlefishh** [comment]
EMP webpages are now editable in markdown format [here](https://github.com/biocore/emp/tree/master/website)

**Comment by cuttlefishh** [comment]
**18S Primers**

Info from Gail:

"Sequenced on the Illumina HiSeq at CU.  Primers 1391f and EukBr were designed for this experiment based on Amaral Zettler 2009 and target the V9 region of the 18S rRNA.  A blocking primer for vertebrate 18S rRNA and used at 4x the concentration of the PCR primers (Mammal_block_I-short_1391f) following the based strategy of Vestheim et al. 2008.  The blocking primer is an exact match to the human sequence. It has a 7 bp overlap with the 3' end of the 1391f primer and extends 33 bp (including a stretch of 5 inosines), and has a 3' spacer at the 3' end to block PCR extension.  The reverse PCR primer (EukBr) is barcoded with a 12-base errorcorrecting Golay code to facilitate multiplexing of up to Å1,500 samples per lane, and both PCR primers contain sequencer adapter regions. The three sequencing primers include two for reading in from each end of the amplicon and a third for reading the barcode.  Polymerase Chain Reaction. Sample preparation was performed similarly to that described by Costello et al. (1). Briefly, each sample was amplified in triplicate and combined. PCR reactions contained 8 uL MO BIO PCR water, 10 uL 5 Prime Hot Master Mix, 1 uL each of the forward and reverse primers (10 uM final concentration), 4 uL mammal blocking primer and 1.0 uL genomic DNA. Reactions were held at 94çC for 3 min to denature the DNA, with amplification proceeding for 40 cycles at 94 çC for 45 s, 65 C for 15 s, 57 çC for 60 s, and 72 çC for 90 s; a final extension of 10 min at 72 çC was added to ensure complete ampli_cation. Amplicons were quantified using Picogreen dsDNA reagent in 10 mM Tris buffer (pH 8.0). A composite sample for sequencing was created by combining equimolar ratios of amplicons from the individual samples, and cleaned using the MO BIO  PCR clean up kit. "
Laura Wegener Parfrey developed the protocol for the lab.

There is also a protocol the Greg Caporaso developed:
18S rRNA Amplification Protocol : Earth Microbiome Project
www.earthmicrobiome.org/emp-standard-protocols/18s/
Caporaso JG, Lauber CL, Walters WA, Berg-Lyons D, Huntley J, Fierer N, Owens SM,... Blocking primers to enhance PCR amplification of rare sequences in mixed samples – a ... Primer Constructs designed by Laura Wegener Parfrey ... particularly useful for host-associated samples with a low biomass of eukaryotic DNA.

**Comment by cuttlefishh** [comment]
**5Prime Polymerase**

Greg said: VWR has a supplier called Quanta that bought 5Prime and they will be providing a reference number so that we can order the same product.

We should update arrivers@lbl.gov and cms446@cornell.edu with the new reference number.
