### ISSUE TITLE
website: Affiliations, Publications, Meetings, Logo

### ISSUE THREAD

**Issue by cuttlefishh** [biocore/emp#51]
These are from c. 2012 and need to be updated.

**Comment by cuttlefishh** [comment]
EMP webpages are now editable in markdown format [here](https://github.com/biocore/emp/tree/master/website)

**Comment by ackermag** [comment]
I will update you in regard to publications I know of that should be in the
list

On Thu, Mar 10, 2016 at 2:13 PM, Luke Thompson <notifications@github.com>
wrote:

> EMP webpages are now editable in markdown format here
> <https://github.com/biocore/emp/tree/master/website>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/emp/issues/51#issuecomment-195074931>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by cuttlefishh** [comment]
Thanks, Gail. We might might a google scholar search on "earth microbiome project".

**Comment by ackermag** [comment]
Not all of them acknowledged the EMP - I had to mention that to Torsten
Thomas...

On Thu, Mar 10, 2016 at 9:37 PM, Luke Thompson <notifications@github.com>
wrote:

> Thanks, Gail. We might might a google scholar search on "earth microbiome
> project".
>
> > On Mar 10, 2016, at 8:49 PM, Gail Ackermann <notifications@github.com>
> wrote:
> >
> > I will update you in regard to publications I know of that should be in
> the
> > list
> >
> > On Thu, Mar 10, 2016 at 2:13 PM, Luke Thompson <notifications@github.com
> >
> > wrote:
> >
> > > EMP webpages are now editable in markdown format here
> > > <https://github.com/biocore/emp/tree/master/website>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/biocore/emp/issues/51#issuecomment-195074931>.
> > >
> >
> >
> >
> > --
> > Gail Ackermann
> > Knight Lab
> > UCSD
> > glackermann@ucsd.edu <ackermag@ucsd.edu>
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/biocore/emp/issues/51#issuecomment-195182082>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/emp/issues/51#issuecomment-195201702>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>
