### ISSUE TITLE
total number of OTUs

### ISSUE THREAD

**Issue by cuttlefishh** [biocore/emp#60]
This is a contentious question, but it might be worth addressing in the paper. Here is what I wrote to Ken Locey about it (July 15, 2016):

We have picked OTUs using a variety of methods for the first ~27,700 samples in the EMP. It's hard to define a microbial species for both technical and philosophical reasons, but the best approximation we have is probably OTUs. Closed-reference methods give a fairly conservative number (mapped to a reference set clustered at 97% ID along the full-length 16S rRNA; we are sequencing only the V4 region). Open-reference (closed-reference plus de novo clustering of remaining sequences) gives a much larger number. Perhaps the fairest number is the number of unique sequences as determined using an error-correction method called Deblur (https://github.com/biocore/deblur). Here are the OTU counts we get using those different methods:

Closed-reference (Greengenes): 69,901
Closed-reference (Silva): 126,730
Open-reference (Greengenes): 11,014,898
Deblur (unique 100-bp sequences): 351,728

I think the most defensible statement would be: There are >350,000 unique (error-corrected) 100-bp 16S rRNA V4 region sequences identified in the EMP dataset to date.

**Comment by antgonza** [comment]
Makes sense but we might need to be careful with substantives. For example, how do you defined fairest and how did you benchmark it? What about deblur vs. other algorithms, like dada2.

**Comment by cuttlefishh** [comment]
Honestly, we should probably stay away from this question. But somebody asked us about it recently so it was on my mind. For many reasons, it's borderline unanswerable and meaningless.

**Comment by antgonza** [comment]
Should we close or label as wontfix?

**Comment by cuttlefishh** [comment]
Close I guess.
