### ISSUE TITLE
discrepancy in 806rB reverse primer sequence

### ISSUE THREAD

**Issue by thwilkinson** [biocore/emp#68]
Referring to the "16S rRNA Amplification Protocol" section, I noticed that the sequence of the 806rB reverse primer in the file "515f_806_16S_illumina_amplification_protocol_version_6_15.doc" (see page 2) is different from the 806rB sequence found in the file "515f-806rb_new.xls" (see sheet 1 of this Excel spreadsheet).

The difference is a single nucleotide (highlighted in bold below) within the "Primer Pad" region:

806rb sequence from 16S rRNA Amplification protocol version 6_15 (page 2):  CAAGCAGAAGACGGCATACGAGATAGTCAG**T**CAGCCGGACTACNVGGGTWTCTAAT

806rb sequence from "515f_806rb_new.xls" spreadsheet (sheet 1):
CAAGCAGAAGACGGCATACGAGATAGTCAG**C**CAGCCGGACTACNVGGGTWTCTAAT

Which is the correct sequence for this 806rB reverse primer?  I wish to order this primer, and would like to submit the correct sequence for synthesis.  

Please let me know if my question is better posed elsewhere on this forum.  Thanks!

**Comment by cuttlefishh** [comment]
Hi,

This is the correct sequence for the reverse primer:

Reverse primer:
From link “Current Illumina HiSeq 16S Primer Sequences (515f – 806rB)”​
CAAGCAGAAGACGGCATACGAGATAGTCAGCCAGCCGGACTACNVGGGTWTCTAAT

This is the correct sequence for the Read 2 seq primer:

Read 2 Sequencing Primer:
From link “Current Illumina HiSeq 16S Primer Sequences (515f – 806rB)”​
AGTCAGCCAGCCGGACTACNVGGGTWTCTAAT

This is the correct sequence for Index seq primer:

Index Sequence Primer
From link “Current Illumina HiSeq 16S Primer Sequences (515f – 806rB)”​​
AATGATACGGCGACCACCGAGATCTACACGCT


I will get that .doc updated.

Thanks!
Luke

**Comment by thwilkinson** [comment]
Thanks very much!!
Tom

**Comment by cuttlefishh** [comment]
Website is now updated:

http://www.earthmicrobiome.org/emp-standard-protocols/16s/
http://www.earthmicrobiome.org/emp-standard-protocols/18s/
http://www.earthmicrobiome.org/emp-standard-protocols/its/

**Comment by thwilkinson** [comment]
Luke, thank you for posting the updated 16S protocols on the website.

I have a new question, regarding the recipe for the PCR reaction mixture in
the new 16S protocol.  The PCR master mix component is given as 10 µL of 2X
PCR master mix (Platinum Hot Start from ThermoFisher) in a total volume of
25 µL.

Is 10 µL of 2X PCR master mix indeed what is used in practice?  Should not
the volume of the 2X PCR master mix be given as 12.5 µL, if the total
reaction volume is 25 µL?  Just double-checking.

Thanks!
Tom

**Comment by cuttlefishh** [comment]
Hi Tom,

Thanks for your question. 

The protocol is correct as written. The final concentration of master mix is <1x. In our experience, the protocol works fine this way and it leads to significant cost savings over many thousands of samples.

I can add a note to the protocol if this is confusing.

Cheers,
Luke

**Comment by thwilkinson** [comment]
Hi Luke,

Thanks for your explanation - and hearing about your experience using < 1X
concentration master mix was reassuring.  Yes, perhaps adding a note could
provide added clarity to others that are preparing these PCR reactions.

Best regards,
Tom

**Comment by cuttlefishh** [comment]
Hi Tom, I have added clarification to the protocol. Thanks!

**Comment by TheaWhitman** [comment]
Hi Luke,

Another quick clarification question about these primers - the Illumina 5' adapter sequence / sequencing primer (AATGATACGGCGACCACCGAGATCTACACGCT) has an extra GCT at the end compared to Illumina's usual index primer [sequences](http://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/experiment-design/illumina-adapter-sequences_1000000002694-01.pdf). Is that GCT the pad region added to keep the Tm around 66°C, as described in Walters et al. (2015)?

Thanks!
Thea

**Comment by walterst** [comment]
Hello Thea,

Yes, those added bases were placed on the 3' end of the Illumina 5' adapter sequence to increase the Tm for read 1 during sequencing, as you surmised.

-Tony

**Comment by TheaWhitman** [comment]
Hi Tony,

Thanks so much!

Cheers,
Thea

On Dec 5, 2016, at 12:29 AM, Tony <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Thea,

Yes, those added bases were placed on the 3' end of the Illumina 5' adapter sequence to increase the Tm for read 1 during sequencing, as you surmised.

-Tony

**Comment by cuttlefishh** [comment]
Thanks for the clarification, Thea and Tony! I have added this to the website, and will close this issue.
