### ISSUE TITLE
Adding Golay seqs to 16S reverse primers for dual barcoding

### ISSUE THREAD

**Issue by tarunaaggarwal** [biocore/emp#78]
Hello. Our lab is trying to develop 16S sequencing protocol and we'd like to have barcodes on both the forward and reverse primers. We are using the first 25 forward primers (515f) with golay barcodes and I was wondering if we can just copy the next 25 golay barcodes from the forward primers and paste them in the appropriate place within the reverse primer sequence to have dual barcoding.

If someone can advice on how to develop barcoded reverse primers for 16S, that would be great.

Thank you!

**Comment by immrosadi00** [comment]
Sorry, may I ask, how to do this? I also plan to create barcoding primer in both forward and reverse. And how about the PCR cycle conditions.
