### ISSUE TITLE
raw data not available

### ISSUE THREAD

**Issue by rrohwer** [biocore/emp#79]
According to your ReadMe:

>  All per-study raw data is publicly available through the EMP Portal of the Qiita database.

However, only processed biome files are available; the fastq and fasta files are not available (that I could find). Are these available on a raw data repository that handles large files such as NCBI's SRA instead? I could not find any links to that though. In order for open science to be truly open, raw data should also be available.  

Thanks!  
Robin

**Comment by antgonza** [comment]
Hi @rrohwer, you can download the fna, fastq or demux (this is an internal format and we suggest not using it) versions of the demuxed files from the demuxed artifact. 

For example:
![donwload_demux](https://cloud.githubusercontent.com/assets/2014559/26119670/4590b256-3a2b-11e7-8167-2cb428ac2e66.gif)

**Comment by jeffkimbrel** [comment]
Hi,

Where is the link the webpage seen in the screen shot? I too am having trouble locating the raw data.

Thanks,

Jeff

**Comment by antgonza** [comment]
There is no one single link for all raw data as they are different studies. However, if you know the study_id in qiita for the study you are looking for you can simply go to:
https://qiita.ucsd.edu/study/description/[study-id], like for Moving Pictures (study id: 550) is: https://qiita.ucsd.edu/study/description/550

**Comment by cuttlefishh** [comment]
Hi @rrohwer, you should be able to download the raw data now using scripts in https://github.com/biocore/emp/tree/master/code/download-sequences. Please let me know if you have any problems!

**Comment by chloelulu** [comment]
Hi, @antgonza 
I still can not download the raw fastq file in the qiita. Such as this link, https://qiita.ucsd.edu/study/description/10317
There is not raw fastq.gz file. But only the seq.demux. seq.fastq, and so on.
May I know anything wrong with me? 
Thanks

**Comment by rrohwer** [comment]
@chloelulu another way to get the raw fastq files is from the EBI accession number, which is listed on the page you linked.
