### ISSUE TITLE
Website (http://www.earthmicrobiome.org) hyperlinks broken

### ISSUE THREAD

**Issue by adswafford** [biocore/emp#92]
Not certain this is the right place to file this bug, but I didn't see a help account so on two of the pages on the http://www.earthmicrobiome.org website (http://press.igsb.anl.gov/earthmicrobiome/protocols-and-standards/metadata-guide/ and http://www.earthmicrobiome.org/protocols-and-standards/ , the "EMP Ontology" hyperlinks send to http://press.igsb.anl.gov/earthmicrobiome/protocols-and-standards/emp-ontology-empo/ instead of http://press.igsb.anl.gov/earthmicrobiome/protocols-and-standards/empo/

**Comment by cuttlefishh** [comment]
Thanks for catching that, @adswafford! I shortened the URL but failed to update links to it. Should be all good now.

**Comment by adswafford** [comment]
No worries. I'm looking forward to the symposium next week, and exploring in preparation :-)

**Comment by cuttlefishh** [comment]
There are one or two pages on the website that are still outdated. If you’re able to help edit those before next Wed, that would be great. I’ll be in the KL office tomorrow if it works to discuss then.
